version: '3'

services:
  xxl-job-admin:
    image: xuxueli/xxl-job-admin:2.1.2
    container_name: xxl-job-admin
    environment:
        PARAMS: "--spring.datasource.url=jdbc:mysql://xxl-job-mysql:3306/xxl_job?Unicode=true&characterEncoding=UTF-8 --spring.datasource.username=test --spring.datasource.password=MyPass@123"
    networks:
      - mainnetwork
    volumes:
      - /tmp:/data/applogs
    expose:
      - "8080"
    ports:
      - "8080:8080"
      
  xxl-job-mysql:
    image: mysql:5.7.24
    container_name: xxl-job-mysql
    command: ["--default-authentication-plugin=mysql_native_password", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "MyPass@123"
      MYSQL_DATABASE: "xxl_job"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "MyPass@123"
    networks:
      - mainnetwork
    volumes:
      - ../doc/db/tables_xxl_job.sql:/docker-entrypoint-initdb.d/tables_xxl_job.sql # 如果不需要初始化数据可以注释掉本行。
    expose:
      - "3306"
    ports:
      - "3306:3306"
    
networks:
  mainnetwork:
    driver: "bridge"



